//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviepro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMovieEntities : DbContext
    {
        public DBMovieEntities()
            : base("name=DBMovieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TSql_Banner> TSql_Banner { get; set; }
        public virtual DbSet<TSql_Categorys> TSql_Categorys { get; set; }
        public virtual DbSet<TSql_Chat> TSql_Chat { get; set; }
        public virtual DbSet<TSql_Comment> TSql_Comment { get; set; }
        public virtual DbSet<TSql_Country> TSql_Country { get; set; }
        public virtual DbSet<TSql_Film_Category> TSql_Film_Category { get; set; }
        public virtual DbSet<TSql_Films> TSql_Films { get; set; }
        public virtual DbSet<TSql_Informations> TSql_Informations { get; set; }
        public virtual DbSet<TSql_Reply> TSql_Reply { get; set; }
    }
}
