//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviepro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Reply
    {
        public int IDReply { get; set; }
        public int IDComment { get; set; }
        public string Reply { get; set; }
        public Nullable<int> IDInfo { get; set; }
        public Nullable<System.DateTime> DatePost { get; set; }
    
        public virtual TSql_Comment TSql_Comment { get; set; }
        public virtual TSql_Informations TSql_Informations { get; set; }
    }
}
