//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviepro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Films
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_Films()
        {
            this.TSql_Comment = new HashSet<TSql_Comment>();
            this.TSql_Film_Category = new HashSet<TSql_Film_Category>();
        }
    
        public int IDFilm { get; set; }
        public string FilmName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Time { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DateSubmited { get; set; }
        public string Image { get; set; }
        public Nullable<int> IDCountry { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<int> Views { get; set; }
        public string LinkFilm { get; set; }
        public string Trailer { get; set; }
        public string Download { get; set; }
        public string Languages { get; set; }
        public Nullable<int> Votes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Comment> TSql_Comment { get; set; }
        public virtual TSql_Country TSql_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Film_Category> TSql_Film_Category { get; set; }
    }
}
