//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviepro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class TSql_Informations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_Informations()
        {
            this.TSql_Chat = new HashSet<TSql_Chat>();
            this.TSql_Comment = new HashSet<TSql_Comment>();
            this.TSql_Reply = new HashSet<TSql_Reply>();
        }

        public int IDInfo { get; set; }
        [Required]
        public string DisplayName { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [Remote("CheckUser", "Accounts", HttpMethod = "POST", ErrorMessage = "Account have exist")]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [System.Web.Mvc.Compare("Password", ErrorMessage = "Pasword incorrect")]
        public string ConfirmPassword { get; set; }
        public int Role { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string ForgotPasswordCode { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Chat> TSql_Chat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Comment> TSql_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Reply> TSql_Reply { get; set; }
    }
}
