//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviepro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Chat
    {
        public int IDChat { get; set; }
        public string Chat { get; set; }
        public Nullable<System.DateTime> DateChat { get; set; }
        public Nullable<int> IDUser { get; set; }
    
        public virtual TSql_Informations TSql_Informations { get; set; }
    }
}
