//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moviepro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSql_Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSql_Comment()
        {
            this.TSql_Reply = new HashSet<TSql_Reply>();
        }
    
        public int IDComment { get; set; }
        public int IDFilm { get; set; }
        public Nullable<int> IDInfo { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DatePost { get; set; }
    
        public virtual TSql_Films TSql_Films { get; set; }
        public virtual TSql_Informations TSql_Informations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSql_Reply> TSql_Reply { get; set; }
    }
}
